spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: local
    password: localpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

security:
  enable-csrf: false